```
@作者: 阿凯爱玩机器人
@QQ: 244561792
@微信: xingshunkai
@邮箱: xingshunkai@qq.com
@网址: deepsenserobot.com
@B站: "阿凯爱玩机器人"
```

## 导入依赖

In [1]:
import copy
import numpy as np
import cv2
from matplotlib import pyplot as plt
import open3d as o3d

# 自定义库
from kyle_robot_toolbox.transform import Transform
from kyle_robot_toolbox.open3d import *

np.set_printoptions(precision=5, suppress=True)

pybullet build time: Jun  3 2022 02:05:55


## 载入数据

In [2]:
# 载入相机到标定板的空间变换
T_cam2board = np.load("data/example/draw_camera/T_cam2board.npy")
print(f"T_cam2board: \n{T_cam2board}")

# 相机内参
intrinsic = np.load("data/example/draw_camera/intrinsic.npy")
print(f"Camera Intrinsic:  \n{intrinsic}")

T_cam2board: 
[[ 0.99963  0.01352 -0.02364 -0.00883]
 [ 0.0115  -0.99643 -0.0836  -0.06985]
 [-0.02468  0.0833  -0.99622  0.7825 ]
 [ 0.       0.       0.       1.     ]]
Camera Intrinsic:  
[[608.099   0.    338.379]
 [  0.    609.32  240.369]
 [  0.      0.      1.   ]]


## 绘制相机模型 + 标定板坐标系

In [3]:
# 相机在世界坐标系下的位姿
T_world2cam = np.eye(4)

# 图像尺寸
img_width = 640
img_height = 480
# 可视化相机平面距离相机坐标系原点距离
# 单位m
panel_distance = 0.1

camera_geometries = geometry_camera(intrinsic, T_world2cam, \
        img_width, img_height, \
        panel_distance = panel_distance, \
        color=[0.8, 0.2, 0.2], \
        draw_panel=False)

# 标定板坐标系
coord_board = geometry_coordinate(T_cam2board, size=0.15)

## 绘制标定板模型

In [4]:
# 获取标定板尺寸
# 单位: mm -> m
board_width = 0.6
board_height = 0.4
board_depth = 0.002 # 标定板厚度 # 0.002

print(f"标定板 宽度:{board_width:3f} 高度:{board_height:.3f}  深度:{board_depth}")

标定板 宽度:0.600000 高度:0.400  深度:0.002


In [5]:
board = geometry_box(T_cam2board, board_width, board_height, box_depth=board_depth, color=[0.5, 0.5, 0.5])
# 同时绘制相机模型与标定板坐标系+标定板
draw_geometry(camera_geometries + [coord_board, board], bk_color=[1, 1, 1])